version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/backend"
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: "/backend"
    schedule:
      interval: daily
    open-pull-requests-limit: 100
